# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20daef2506e366309c5965cc457962ba4e1e1d930633cedbe6d58dc4291e25147b217e244b9571e9bf3cf76a3b671fc7d73b3770ef5c7161a9931027f75e66b4

test:
  secret_key_base: 094260ef330bc1c7b972027793259c3ff70d414a27576c5aa1dca26aa00725b802c1086443c04170a662165d8120ef3a6c7c933adfe1679f2d470f2926ed4d0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
